# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'diffviewerdialog.ui'
#
# Created: Mon Apr 14 13:59:47 2014
#      by: PyQt4 UI code generator 4.9.6
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_DiffViewerDialog(object):
    def setupUi(self, DiffViewerDialog):
        DiffViewerDialog.setObjectName(_fromUtf8("DiffViewerDialog"))
        DiffViewerDialog.resize(1006, 712)
        DiffViewerDialog.setStyleSheet(_fromUtf8("#DiffViewer3 {\n"
"   background-color: #eeeeee;\n"
"\n"
"}"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(DiffViewerDialog)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.groupBox = QtGui.QGroupBox(DiffViewerDialog)
        self.groupBox.setMaximumSize(QtCore.QSize(16777215, 100))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.groupBox)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label_2 = QtGui.QLabel(self.groupBox)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_2.addWidget(self.label_2)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.commit1Widget = QtGui.QWidget(self.groupBox)
        self.commit1Widget.setObjectName(_fromUtf8("commit1Widget"))
        self.horizontalLayout_4.addWidget(self.commit1Widget)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_8 = QtGui.QVBoxLayout()
        self.verticalLayout_8.setSpacing(0)
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        spacerItem1 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        self.verticalLayout_8.addItem(spacerItem1)
        self.horizontalLayout.addLayout(self.verticalLayout_8)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.label_4 = QtGui.QLabel(self.groupBox)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout_5.addWidget(self.label_4)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem2)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.commit2Widget = QtGui.QWidget(self.groupBox)
        self.commit2Widget.setObjectName(_fromUtf8("commit2Widget"))
        self.horizontalLayout_6.addWidget(self.commit2Widget)
        self.verticalLayout_2.addLayout(self.horizontalLayout_6)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout_5.addWidget(self.groupBox)
        spacerItem3 = QtGui.QSpacerItem(20, 10, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.verticalLayout_5.addItem(spacerItem3)
        self.splitter_2 = QtGui.QSplitter(DiffViewerDialog)
        self.splitter_2.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_2.setObjectName(_fromUtf8("splitter_2"))
        self.featuresTreeWidget = QtGui.QTreeWidget(self.splitter_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.featuresTreeWidget.sizePolicy().hasHeightForWidth())
        self.featuresTreeWidget.setSizePolicy(sizePolicy)
        self.featuresTreeWidget.setMinimumSize(QtCore.QSize(0, 0))
        self.featuresTreeWidget.setMaximumSize(QtCore.QSize(213213, 16777215))
        self.featuresTreeWidget.setObjectName(_fromUtf8("featuresTreeWidget"))
        self.groupBox_3 = QtGui.QGroupBox(self.splitter_2)
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_6.setContentsMargins(9, 9, -1, -1)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.splitter = QtGui.QSplitter(self.groupBox_3)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName(_fromUtf8("splitter"))
        self.attributesTable = QtGui.QTableWidget(self.splitter)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.attributesTable.sizePolicy().hasHeightForWidth())
        self.attributesTable.setSizePolicy(sizePolicy)
        self.attributesTable.setMinimumSize(QtCore.QSize(568, 0))
        self.attributesTable.setMaximumSize(QtCore.QSize(16777215, 200))
        self.attributesTable.setStyleSheet(_fromUtf8("#featureDetailsTableWidget::section {\n"
"    background: yellow;\n"
"    border: 2px outset yellow;\n"
"}"))
        self.attributesTable.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.attributesTable.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.attributesTable.setProperty("showDropIndicator", False)
        self.attributesTable.setDragDropOverwriteMode(False)
        self.attributesTable.setAlternatingRowColors(False)
        self.attributesTable.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.attributesTable.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.attributesTable.setShowGrid(True)
        self.attributesTable.setGridStyle(QtCore.Qt.DotLine)
        self.attributesTable.setWordWrap(False)
        self.attributesTable.setObjectName(_fromUtf8("attributesTable"))
        self.attributesTable.setColumnCount(3)
        self.attributesTable.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        item.setFont(font)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setForeground(brush)
        self.attributesTable.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        item.setBackground(QtGui.QColor(0, 0, 0, 0))
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setForeground(brush)
        self.attributesTable.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        item.setFont(font)
        self.attributesTable.setHorizontalHeaderItem(2, item)
        self.attributesTable.horizontalHeader().setCascadingSectionResizes(True)
        self.attributesTable.horizontalHeader().setDefaultSectionSize(180)
        self.attributesTable.horizontalHeader().setMinimumSectionSize(30)
        self.attributesTable.horizontalHeader().setStretchLastSection(True)
        self.attributesTable.verticalHeader().setVisible(False)
        self.attributesTable.verticalHeader().setCascadingSectionResizes(True)
        self.attributesTable.verticalHeader().setStretchLastSection(False)
        self.mapTabWidget = QtGui.QTabWidget(self.splitter)
        self.mapTabWidget.setObjectName(_fromUtf8("mapTabWidget"))
        self.splitmap = QtGui.QWidget()
        self.splitmap.setObjectName(_fromUtf8("splitmap"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.splitmap)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.label_6 = QtGui.QLabel(self.splitmap)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.horizontalLayout_10.addWidget(self.label_6)
        spacerItem4 = QtGui.QSpacerItem(40, 0, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem4)
        self.showLayerSplitMap1Check = QtGui.QCheckBox(self.splitmap)
        self.showLayerSplitMap1Check.setObjectName(_fromUtf8("showLayerSplitMap1Check"))
        self.horizontalLayout_10.addWidget(self.showLayerSplitMap1Check)
        spacerItem5 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem5)
        self.zoomToCommit1Button = QtGui.QToolButton(self.splitmap)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/icon/zoom-extent.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.zoomToCommit1Button.setIcon(icon)
        self.zoomToCommit1Button.setIconSize(QtCore.QSize(24, 24))
        self.zoomToCommit1Button.setAutoRaise(False)
        self.zoomToCommit1Button.setObjectName(_fromUtf8("zoomToCommit1Button"))
        self.horizontalLayout_10.addWidget(self.zoomToCommit1Button)
        self.horizontalLayout_9.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_11 = QtGui.QHBoxLayout()
        self.horizontalLayout_11.setObjectName(_fromUtf8("horizontalLayout_11"))
        self.label_7 = QtGui.QLabel(self.splitmap)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.horizontalLayout_11.addWidget(self.label_7)
        spacerItem6 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem6)
        self.showLayerSplitMap2Check = QtGui.QCheckBox(self.splitmap)
        self.showLayerSplitMap2Check.setObjectName(_fromUtf8("showLayerSplitMap2Check"))
        self.horizontalLayout_11.addWidget(self.showLayerSplitMap2Check)
        spacerItem7 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem7)
        self.zoomToCommit2Button = QtGui.QToolButton(self.splitmap)
        self.zoomToCommit2Button.setIcon(icon)
        self.zoomToCommit2Button.setIconSize(QtCore.QSize(24, 24))
        self.zoomToCommit2Button.setObjectName(_fromUtf8("zoomToCommit2Button"))
        self.horizontalLayout_11.addWidget(self.zoomToCommit2Button)
        self.horizontalLayout_9.addLayout(self.horizontalLayout_11)
        self.verticalLayout_3.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.splitMapWidget = QtGui.QWidget(self.splitmap)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.splitMapWidget.sizePolicy().hasHeightForWidth())
        self.splitMapWidget.setSizePolicy(sizePolicy)
        self.splitMapWidget.setObjectName(_fromUtf8("splitMapWidget"))
        self.horizontalLayout_8.addWidget(self.splitMapWidget)
        self.splitMapWidget2 = QtGui.QWidget(self.splitmap)
        self.splitMapWidget2.setObjectName(_fromUtf8("splitMapWidget2"))
        self.horizontalLayout_8.addWidget(self.splitMapWidget2)
        self.verticalLayout_3.addLayout(self.horizontalLayout_8)
        self.mapTabWidget.addTab(self.splitmap, _fromUtf8(""))
        self.singlemap = QtGui.QWidget()
        self.singlemap.setObjectName(_fromUtf8("singlemap"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.singlemap)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.horizontalLayout_12 = QtGui.QHBoxLayout()
        self.horizontalLayout_12.setObjectName(_fromUtf8("horizontalLayout_12"))
        spacerItem8 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem8)
        self.showLayerSingleMapCheck = QtGui.QCheckBox(self.singlemap)
        self.showLayerSingleMapCheck.setObjectName(_fromUtf8("showLayerSingleMapCheck"))
        self.horizontalLayout_12.addWidget(self.showLayerSingleMapCheck)
        spacerItem9 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem9)
        self.zoomToSingleMapButton = QtGui.QToolButton(self.singlemap)
        self.zoomToSingleMapButton.setText(_fromUtf8(""))
        self.zoomToSingleMapButton.setIcon(icon)
        self.zoomToSingleMapButton.setIconSize(QtCore.QSize(24, 24))
        self.zoomToSingleMapButton.setObjectName(_fromUtf8("zoomToSingleMapButton"))
        self.horizontalLayout_12.addWidget(self.zoomToSingleMapButton)
        self.verticalLayout_4.addLayout(self.horizontalLayout_12)
        self.singleMapWidget = QtGui.QWidget(self.singlemap)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.singleMapWidget.sizePolicy().hasHeightForWidth())
        self.singleMapWidget.setSizePolicy(sizePolicy)
        self.singleMapWidget.setObjectName(_fromUtf8("singleMapWidget"))
        self.verticalLayout_4.addWidget(self.singleMapWidget)
        self.mapTabWidget.addTab(self.singlemap, _fromUtf8(""))
        self.verticalLayout_6.addWidget(self.splitter)
        self.verticalLayout_5.addWidget(self.splitter_2)

        self.retranslateUi(DiffViewerDialog)
        self.mapTabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(DiffViewerDialog)

    def retranslateUi(self, DiffViewerDialog):
        DiffViewerDialog.setWindowTitle(_translate("DiffViewerDialog", "Diff Viewer", None))
        self.groupBox.setTitle(_translate("DiffViewerDialog", "Commits to Compare", None))
        self.label_2.setText(_translate("DiffViewerDialog", "Before", None))
        self.label_4.setText(_translate("DiffViewerDialog", "After", None))
        self.featuresTreeWidget.headerItem().setText(0, _translate("DiffViewerDialog", "Layers", None))
        self.groupBox_3.setTitle(_translate("DiffViewerDialog", "Details of Each Change:", None))
        self.attributesTable.setSortingEnabled(True)
        item = self.attributesTable.horizontalHeaderItem(0)
        item.setText(_translate("DiffViewerDialog", "Before", None))
        item = self.attributesTable.horizontalHeaderItem(1)
        item.setText(_translate("DiffViewerDialog", "ATTRIBUTES", None))
        item = self.attributesTable.horizontalHeaderItem(2)
        item.setText(_translate("DiffViewerDialog", "After", None))
        self.label_6.setText(_translate("DiffViewerDialog", "Before", None))
        self.showLayerSplitMap1Check.setText(_translate("DiffViewerDialog", "Show base layer", None))
        self.zoomToCommit1Button.setText(_translate("DiffViewerDialog", "ʘ", None))
        self.label_7.setText(_translate("DiffViewerDialog", "After", None))
        self.showLayerSplitMap2Check.setText(_translate("DiffViewerDialog", "Show base layer", None))
        self.zoomToCommit2Button.setToolTip(_translate("DiffViewerDialog", "Zoom to feature extent", None))
        self.zoomToCommit2Button.setText(_translate("DiffViewerDialog", "ʘ", None))
        self.mapTabWidget.setTabText(self.mapTabWidget.indexOf(self.splitmap), _translate("DiffViewerDialog", "Split Map", None))
        self.showLayerSingleMapCheck.setText(_translate("DiffViewerDialog", "Show base layer", None))
        self.mapTabWidget.setTabText(self.mapTabWidget.indexOf(self.singlemap), _translate("DiffViewerDialog", "Single Map", None))

import geogitclient_resources_rc
