# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'githubselectordialog.ui'
#
# Created: Tue Feb 11 16:52:55 2014
#      by: PyQt4 UI code generator 4.9.6
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_GitHubSelectorDialog(object):
    def setupUi(self, GitHubSelectorDialog):
        GitHubSelectorDialog.setObjectName(_fromUtf8("GitHubSelectorDialog"))
        GitHubSelectorDialog.resize(427, 254)
        self.verticalLayout_3 = QtGui.QVBoxLayout(GitHubSelectorDialog)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.groupBox = QtGui.QGroupBox(GitHubSelectorDialog)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.groupBox)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label = QtGui.QLabel(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMaximumSize(QtCore.QSize(80, 16777215))
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout.addWidget(self.label)
        self.userBox = QtGui.QLineEdit(self.groupBox)
        self.userBox.setObjectName(_fromUtf8("userBox"))
        self.horizontalLayout.addWidget(self.userBox)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label_2 = QtGui.QLabel(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setMaximumSize(QtCore.QSize(80, 16777215))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_2.addWidget(self.label_2)
        self.passwordBox = QtGui.QLineEdit(self.groupBox)
        self.passwordBox.setEchoMode(QtGui.QLineEdit.Password)
        self.passwordBox.setObjectName(_fromUtf8("passwordBox"))
        self.horizontalLayout_2.addWidget(self.passwordBox)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.verticalLayout_3.addWidget(self.groupBox)
        self.groupBox_2 = QtGui.QGroupBox(GitHubSelectorDialog)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.verticalLayout = QtGui.QVBoxLayout(self.groupBox_2)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.owner = QtGui.QLabel(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.owner.sizePolicy().hasHeightForWidth())
        self.owner.setSizePolicy(sizePolicy)
        self.owner.setMaximumSize(QtCore.QSize(80, 16777215))
        self.owner.setObjectName(_fromUtf8("owner"))
        self.horizontalLayout_3.addWidget(self.owner)
        self.ownerBox = QtGui.QLineEdit(self.groupBox_2)
        self.ownerBox.setEchoMode(QtGui.QLineEdit.Normal)
        self.ownerBox.setObjectName(_fromUtf8("ownerBox"))
        self.horizontalLayout_3.addWidget(self.ownerBox)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.label_4 = QtGui.QLabel(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setMaximumSize(QtCore.QSize(80, 16777215))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout_4.addWidget(self.label_4)
        self.nameBox = QtGui.QComboBox(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.nameBox.sizePolicy().hasHeightForWidth())
        self.nameBox.setSizePolicy(sizePolicy)
        self.nameBox.setEditable(True)
        self.nameBox.setObjectName(_fromUtf8("nameBox"))
        self.horizontalLayout_4.addWidget(self.nameBox)
        self.fetchReposButton = QtGui.QToolButton(self.groupBox_2)
        self.fetchReposButton.setObjectName(_fromUtf8("fetchReposButton"))
        self.horizontalLayout_4.addWidget(self.fetchReposButton)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.label_3 = QtGui.QLabel(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setMaximumSize(QtCore.QSize(86, 16777215))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout_5.addWidget(self.label_3)
        self.repoFolderBox = QtGui.QLineEdit(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.repoFolderBox.sizePolicy().hasHeightForWidth())
        self.repoFolderBox.setSizePolicy(sizePolicy)
        self.repoFolderBox.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.repoFolderBox.setText(_fromUtf8(""))
        self.repoFolderBox.setObjectName(_fromUtf8("repoFolderBox"))
        self.horizontalLayout_5.addWidget(self.repoFolderBox)
        self.selectRepoFolderButton = QtGui.QToolButton(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.selectRepoFolderButton.sizePolicy().hasHeightForWidth())
        self.selectRepoFolderButton.setSizePolicy(sizePolicy)
        self.selectRepoFolderButton.setMinimumSize(QtCore.QSize(0, 21))
        self.selectRepoFolderButton.setMaximumSize(QtCore.QSize(16777215, 16677215))
        self.selectRepoFolderButton.setObjectName(_fromUtf8("selectRepoFolderButton"))
        self.horizontalLayout_5.addWidget(self.selectRepoFolderButton)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.verticalLayout_3.addWidget(self.groupBox_2)
        self.buttonBox = QtGui.QDialogButtonBox(GitHubSelectorDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.verticalLayout_3.addWidget(self.buttonBox)

        self.retranslateUi(GitHubSelectorDialog)
        QtCore.QMetaObject.connectSlotsByName(GitHubSelectorDialog)

    def retranslateUi(self, GitHubSelectorDialog):
        GitHubSelectorDialog.setWindowTitle(_translate("GitHubSelectorDialog", "Select GitHub repository", None))
        self.groupBox.setTitle(_translate("GitHubSelectorDialog", "Authentication", None))
        self.label.setText(_translate("GitHubSelectorDialog", "User", None))
        self.label_2.setText(_translate("GitHubSelectorDialog", "Password", None))
        self.groupBox_2.setTitle(_translate("GitHubSelectorDialog", "Repository", None))
        self.owner.setText(_translate("GitHubSelectorDialog", "Owner", None))
        self.ownerBox.setPlaceholderText(_translate("GitHubSelectorDialog", "Leave blank to use user name", None))
        self.label_4.setText(_translate("GitHubSelectorDialog", "Name", None))
        self.fetchReposButton.setText(_translate("GitHubSelectorDialog", "Fetch repos", None))
        self.label_3.setText(_translate("GitHubSelectorDialog", "Local folder", None))
        self.selectRepoFolderButton.setText(_translate("GitHubSelectorDialog", "...", None))

